-- USER SQL
--CREATE USER ACME_USER IDENTIFIED BY admin 
--DEFAULT TABLESPACE "USERS"
--TEMPORARY TABLESPACE "TEMP";

-- ROLES
--GRANT "RESOURCE" TO ACME_USER ;
--GRANT "CONNECT" TO ACME_USER ;

CREATE TABLE TB_CUSTOMER_JULIANO (
    TB_ID NUMBER NOT NULL, 
    TB_NOME VARCHAR2(255), 
    TB_DATA_NASCIMENTO DATE, 
    TB_CPF VARCHAR2(14),
    TB_TELEFONE_PRINCIPAL NUMBER, 
    TB_PORTABILIDADE_STATUS CHAR(1),
    PRIMARY KEY (TB_ID) 
);

CREATE TABLE TB_STATUS_FINANCEIRO_JULIANO (
    TB_CPF VARCHAR2(14),
    TB_STATUS_FINANCEIRO CHAR(1)    
);

CREATE TABLE TB_ACCOUNT_JULIANO (
    TB_NU_CONTA NUMBER NOT NULL, 
    TB_ID_CUSTOMER NUMBER NOT NULL, 
    TB_PLANO VARCHAR2(255), 
    TB_STATUS VARCHAR(50), 
    TB_TELEFONE NUMBER, 
    TB_PORTABILIDADE_STATUS CHAR(1), 
    TB_PORTABILIDADE_DESC VARCHAR2(50), 
    TB_POSSUI_DEBITOS CHAR(1), 
    PRIMARY KEY (TB_NU_CONTA),
    CONSTRAINT fk_Customer_Account_Juliano FOREIGN KEY (TB_ID_CUSTOMER)
    REFERENCES TB_CUSTOMER_JULIANO(TB_ID)
    );
    
insert into tb_status_financeiro_juliano values ('11111111111','O');
insert into tb_customer_juliano values (1,	'Juliano Cervelin',	'12-SEP-1980','11111111111',11999999999 ,'N')  
insert into tb_account_juliano values (12345,	1,	'CONTROLE',	'ATIVO',	11999999999,	'N',NULL,'N')

create or replace 
package INOVIX_JULIANOCERVELIN is

  PROCEDURE update_status_portabilidade(P_CPF in TB_CUSTOMER_JULIANO.TB_CPF%type, P_PORTABILIDADE_STATUS in TB_CUSTOMER_JULIANO.TB_PORTABILIDADE_STATUS%type);

end INOVIX_JULIANOCERVELIN;

create or replace 
package body INOVIX_JULIANOCERVELIN is
  PROCEDURE update_status_portabilidade(P_CPF in TB_CUSTOMER_JULIANO.TB_CPF%type, P_PORTABILIDADE_STATUS in TB_CUSTOMER_JULIANO.TB_PORTABILIDADE_STATUS%type) IS
  BEGIN
    update TB_CUSTOMER_JULIANO set TB_PORTABILIDADE_STATUS = P_PORTABILIDADE_STATUS where TB_CPF = P_CPF;
  END;
end INOVIX_JULIANOCERVELIN;



