<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationAdapterLegacy/AdapterDBCobol/getCustomerByCpf" name="getCustomerByCpf-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationAdapterLegacy/AdapterDBCobol/getCustomerByCpf" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationAdapterLegacy/AdapterDBCobol/getCustomerByCpf" location="../../Adapters/AdapterDBCobol/getCustomerByCpf.wsdl"/>
  <binding name="getCustomerByCpf_ptt-binding" type="tns:getCustomerByCpf_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getCustomerByCpf">
      <soap:operation soapAction="getCustomerByCpf"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getCustomerByCpf-service">
    <port name="getCustomerByCpf-port" binding="tns:getCustomerByCpf_ptt-binding">
      <soap:address location="jca://eis/DB/INOVIX"/>
    </port>
  </service>
</definitions>